/*
 Bootstrap v3.3.7 (http://getbootstrap.com)
 Copyright 2011-2016 Twitter, Inc.
 Licensed under the MIT license
*/
if("undefined"===typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");+function(b){b=b.fn.jquery.split(" ")[0].split(".");if(2>b[0]&&9>b[1]||1==b[0]&&9==b[1]&&1>b[2]||3<b[0])throw Error("Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4");}(jQuery);
+function(b){function f(){var b=document.createElement("bootstrap"),d={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},a;for(a in d)if(void 0!==b.style[a])return{end:d[a]};return!1}b.fn.emulateTransitionEnd=function(e){var d=!1,a=this;b(this).one("bsTransitionEnd",function(){d=!0});setTimeout(function(){d||b(a).trigger(b.support.transition.end)},e);return this};b(function(){b.support.transition=f();b.support.transition&&
(b.event.special.bsTransitionEnd={bindType:b.support.transition.end,delegateType:b.support.transition.end,handle:function(e){if(b(e.target).is(this))return e.handleObj.handler.apply(this,arguments)}})})}(jQuery);
+function(b){var f=function(d){b(d).on("click",'[data-dismiss="alert"]',this.close)};f.VERSION="3.3.7";f.TRANSITION_DURATION=150;f.prototype.close=function(d){function a(){l.detach().trigger("closed.bs.alert").remove()}var c=b(this),g=c.attr("data-target");g||(g=(g=c.attr("href"))&&g.replace(/.*(?=#[^\s]*$)/,""));var l=b("#"===g?[]:g);d&&d.preventDefault();l.length||(l=c.closest(".alert"));l.trigger(d=b.Event("close.bs.alert"));d.isDefaultPrevented()||(l.removeClass("in"),b.support.transition&&l.hasClass("fade")?
l.one("bsTransitionEnd",a).emulateTransitionEnd(f.TRANSITION_DURATION):a())};var e=b.fn.alert;b.fn.alert=function(d){return this.each(function(){var a=b(this),c=a.data("bs.alert");c||a.data("bs.alert",c=new f(this));"string"==typeof d&&c[d].call(a)})};b.fn.alert.Constructor=f;b.fn.alert.noConflict=function(){b.fn.alert=e;return this};b(document).on("click.bs.alert.data-api",'[data-dismiss="alert"]',f.prototype.close)}(jQuery);
+function(b){function f(a){return this.each(function(){var c=b(this),g=c.data("bs.button"),d="object"==typeof a&&a;g||c.data("bs.button",g=new e(this,d));"toggle"==a?g.toggle():a&&g.setState(a)})}var e=function(a,c){this.$element=b(a);this.options=b.extend({},e.DEFAULTS,c);this.isLoading=!1};e.VERSION="3.3.7";e.DEFAULTS={loadingText:"loading..."};e.prototype.setState=function(a){var c=this.$element,g=c.is("input")?"val":"html",d=c.data();a+="Text";null==d.resetText&&c.data("resetText",c[g]());setTimeout(b.proxy(function(){c[g](null==
d[a]?this.options[a]:d[a]);"loadingText"==a?(this.isLoading=!0,c.addClass("disabled").attr("disabled","disabled").prop("disabled",!0)):this.isLoading&&(this.isLoading=!1,c.removeClass("disabled").removeAttr("disabled").prop("disabled",!1))},this),0)};e.prototype.toggle=function(){var a=!0,c=this.$element.closest('[data-toggle="buttons"]');if(c.length){var b=this.$element.find("input");"radio"==b.prop("type")?(b.prop("checked")&&(a=!1),c.find(".active").removeClass("active"),this.$element.addClass("active")):
"checkbox"==b.prop("type")&&(b.prop("checked")!==this.$element.hasClass("active")&&(a=!1),this.$element.toggleClass("active"));b.prop("checked",this.$element.hasClass("active"));a&&b.trigger("change")}else this.$element.attr("aria-pressed",!this.$element.hasClass("active")),this.$element.toggleClass("active")};var d=b.fn.button;b.fn.button=f;b.fn.button.Constructor=e;b.fn.button.noConflict=function(){b.fn.button=d;return this};b(document).on("click.bs.button.data-api",'[data-toggle^="button"]',function(a){var c=
b(a.target).closest(".btn");f.call(c,"toggle");b(a.target).is('input[type="radio"], input[type="checkbox"]')||(a.preventDefault(),c.is("input,button")?c.trigger("focus"):c.find("input:visible,button:visible").first().trigger("focus"))}).on("focus.bs.button.data-api blur.bs.button.data-api",'[data-toggle^="button"]',function(a){b(a.target).closest(".btn").toggleClass("focus",/^focus(in)?$/.test(a.type))})}(jQuery);
+function(b){function f(c){return this.each(function(){var a=b(this),d=a.data("bs.carousel"),f=b.extend({},e.DEFAULTS,a.data(),"object"==typeof c&&c),k="string"==typeof c?c:f.slide;d||a.data("bs.carousel",d=new e(this,f));if("number"==typeof c)d.to(c);else if(k)d[k]();else f.interval&&d.pause().cycle()})}var e=function(c,a){this.$element=b(c);this.$indicators=this.$element.find(".carousel-indicators");this.options=a;this.$items=this.$active=this.interval=this.sliding=this.paused=null;this.options.keyboard&&
this.$element.on("keydown.bs.carousel",b.proxy(this.keydown,this));"hover"!=this.options.pause||"ontouchstart"in document.documentElement||this.$element.on("mouseenter.bs.carousel",b.proxy(this.pause,this)).on("mouseleave.bs.carousel",b.proxy(this.cycle,this))};e.VERSION="3.3.7";e.TRANSITION_DURATION=600;e.DEFAULTS={interval:5E3,pause:"hover",wrap:!0,keyboard:!0};e.prototype.keydown=function(c){if(!/input|textarea/i.test(c.target.tagName)){switch(c.which){case 37:this.prev();break;case 39:this.next();
break;default:return}c.preventDefault()}};e.prototype.cycle=function(c){c||(this.paused=!1);this.interval&&clearInterval(this.interval);this.options.interval&&!this.paused&&(this.interval=setInterval(b.proxy(this.next,this),this.options.interval));return this};e.prototype.getItemIndex=function(c){this.$items=c.parent().children(".item");return this.$items.index(c||this.$active)};e.prototype.getItemForDirection=function(c,a){var b=this.getItemIndex(a);return("prev"==c&&0===b||"next"==c&&b==this.$items.length-
1)&&!this.options.wrap?a:this.$items.eq((b+("prev"==c?-1:1))%this.$items.length)};e.prototype.to=function(c){var a=this,b=this.getItemIndex(this.$active=this.$element.find(".item.active"));if(!(c>this.$items.length-1||0>c))return this.sliding?this.$element.one("slid.bs.carousel",function(){a.to(c)}):b==c?this.pause().cycle():this.slide(c>b?"next":"prev",this.$items.eq(c))};e.prototype.pause=function(c){c||(this.paused=!0);this.$element.find(".next, .prev").length&&b.support.transition&&(this.$element.trigger(b.support.transition.end),
this.cycle(!0));this.interval=clearInterval(this.interval);return this};e.prototype.next=function(){if(!this.sliding)return this.slide("next")};e.prototype.prev=function(){if(!this.sliding)return this.slide("prev")};e.prototype.slide=function(c,a){var d=this.$element.find(".item.active"),g=a||this.getItemForDirection(c,d),f=this.interval,h="next"==c?"left":"right",n=this;if(g.hasClass("active"))return this.sliding=!1;var q=g[0],p=b.Event("slide.bs.carousel",{relatedTarget:q,direction:h});this.$element.trigger(p);
if(!p.isDefaultPrevented()){this.sliding=!0;f&&this.pause();this.$indicators.length&&(this.$indicators.find(".active").removeClass("active"),(p=b(this.$indicators.children()[this.getItemIndex(g)]))&&p.addClass("active"));var r=b.Event("slid.bs.carousel",{relatedTarget:q,direction:h});b.support.transition&&this.$element.hasClass("slide")?(g.addClass(c),g[0].offsetWidth,d.addClass(h),g.addClass(h),d.one("bsTransitionEnd",function(){g.removeClass([c,h].join(" ")).addClass("active");d.removeClass(["active",
h].join(" "));n.sliding=!1;setTimeout(function(){n.$element.trigger(r)},0)}).emulateTransitionEnd(e.TRANSITION_DURATION)):(d.removeClass("active"),g.addClass("active"),this.sliding=!1,this.$element.trigger(r));f&&this.cycle();return this}};var d=b.fn.carousel;b.fn.carousel=f;b.fn.carousel.Constructor=e;b.fn.carousel.noConflict=function(){b.fn.carousel=d;return this};var a=function(a){var c,d=b(this),e=b(d.attr("data-target")||(c=d.attr("href"))&&c.replace(/.*(?=#[^\s]+$)/,""));if(e.hasClass("carousel")){c=
b.extend({},e.data(),d.data());if(d=d.attr("data-slide-to"))c.interval=!1;f.call(e,c);d&&e.data("bs.carousel").to(d);a.preventDefault()}};b(document).on("click.bs.carousel.data-api","[data-slide]",a).on("click.bs.carousel.data-api","[data-slide-to]",a);b(window).on("load",function(){b('[data-ride="carousel"]').each(function(){var c=b(this);f.call(c,c.data())})})}(jQuery);
+function(b){function f(c){var a;c=c.attr("data-target")||(a=c.attr("href"))&&a.replace(/.*(?=#[^\s]+$)/,"");return b(c)}function e(a){return this.each(function(){var c=b(this),l=c.data("bs.collapse"),e=b.extend({},d.DEFAULTS,c.data(),"object"==typeof a&&a);!l&&e.toggle&&/show|hide/.test(a)&&(e.toggle=!1);l||c.data("bs.collapse",l=new d(this,e));if("string"==typeof a)l[a]()})}var d=function(a,g){this.$element=b(a);this.options=b.extend({},d.DEFAULTS,g);this.$trigger=b('[data-toggle="collapse"][href="#'+
a.id+'"],[data-toggle="collapse"][data-target="#'+a.id+'"]');this.transitioning=null;this.options.parent?this.$parent=this.getParent():this.addAriaAndCollapsedClass(this.$element,this.$trigger);this.options.toggle&&this.toggle()};d.VERSION="3.3.7";d.TRANSITION_DURATION=350;d.DEFAULTS={toggle:!0};d.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};d.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a,g=this.$parent&&this.$parent.children(".panel").children(".in, .collapsing");
if(g&&g.length&&(a=g.data("bs.collapse"))&&a.transitioning)return;var l=b.Event("show.bs.collapse");this.$element.trigger(l);if(!l.isDefaultPrevented()){g&&g.length&&(e.call(g,"hide"),a||g.data("bs.collapse",null));var f=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[f](0).attr("aria-expanded",!0);this.$trigger.removeClass("collapsed").attr("aria-expanded",!0);this.transitioning=1;a=function(){this.$element.removeClass("collapsing").addClass("collapse in")[f]("");this.transitioning=
0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return a.call(this);g=b.camelCase(["scroll",f].join("-"));this.$element.one("bsTransitionEnd",b.proxy(a,this)).emulateTransitionEnd(d.TRANSITION_DURATION)[f](this.$element[0][g])}}};d.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=b.Event("hide.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){a=this.dimension();this.$element[a](this.$element[a]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse in").attr("aria-expanded",
!1);this.$trigger.addClass("collapsed").attr("aria-expanded",!1);this.transitioning=1;var g=function(){this.transitioning=0;this.$element.removeClass("collapsing").addClass("collapse").trigger("hidden.bs.collapse")};if(!b.support.transition)return g.call(this);this.$element[a](0).one("bsTransitionEnd",b.proxy(g,this)).emulateTransitionEnd(d.TRANSITION_DURATION)}}};d.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};d.prototype.getParent=function(){return b(this.options.parent).find('[data-toggle="collapse"][data-parent="'+
this.options.parent+'"]').each(b.proxy(function(a,d){var c=b(d);this.addAriaAndCollapsedClass(f(c),c)},this)).end()};d.prototype.addAriaAndCollapsedClass=function(a,b){var c=a.hasClass("in");a.attr("aria-expanded",c);b.toggleClass("collapsed",!c).attr("aria-expanded",c)};var a=b.fn.collapse;b.fn.collapse=e;b.fn.collapse.Constructor=d;b.fn.collapse.noConflict=function(){b.fn.collapse=a;return this};b(document).on("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(a){var c=b(this);c.attr("data-target")||
a.preventDefault();a=f(c);c=a.data("bs.collapse")?"toggle":c.data();e.call(a,c)})}(jQuery);
+function(b){function f(a){var c=a.attr("data-target");c||(c=(c=a.attr("href"))&&/#[A-Za-z]/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));return(c=c&&b(c))&&c.length?c:a.parent()}function e(a){a&&3===a.which||(b(".dropdown-backdrop").remove(),b('[data-toggle="dropdown"]').each(function(){var c=b(this),d=f(c),e={relatedTarget:this};!d.hasClass("open")||a&&"click"==a.type&&/input|textarea/i.test(a.target.tagName)&&b.contains(d[0],a.target)||(d.trigger(a=b.Event("hide.bs.dropdown",e)),a.isDefaultPrevented()||
(c.attr("aria-expanded","false"),d.removeClass("open").trigger(b.Event("hidden.bs.dropdown",e))))}))}var d=function(a){b(a).on("click.bs.dropdown",this.toggle)};d.VERSION="3.3.7";d.prototype.toggle=function(a){var c=b(this);if(!c.is(".disabled, :disabled")){var d=f(c);a=d.hasClass("open");e();if(!a){if("ontouchstart"in document.documentElement&&!d.closest(".navbar-nav").length)b(document.createElement("div")).addClass("dropdown-backdrop").insertAfter(b(this)).on("click",e);var m={relatedTarget:this};
d.trigger(a=b.Event("show.bs.dropdown",m));if(a.isDefaultPrevented())return;c.trigger("focus").attr("aria-expanded","true");d.toggleClass("open").trigger(b.Event("shown.bs.dropdown",m))}return!1}};d.prototype.keydown=function(a){if(/(38|40|27|32)/.test(a.which)&&!/input|textarea/i.test(a.target.tagName)){var c=b(this);a.preventDefault();a.stopPropagation();if(!c.is(".disabled, :disabled")){var d=f(c),e=d.hasClass("open");if(!e&&27!=a.which||e&&27==a.which)return 27==a.which&&d.find('[data-toggle="dropdown"]').trigger("focus"),
c.trigger("click");c=d.find(".dropdown-menu li:not(.disabled):visible a");c.length&&(d=c.index(a.target),38==a.which&&0<d&&d--,40==a.which&&d<c.length-1&&d++,~d||(d=0),c.eq(d).trigger("focus"))}}};var a=b.fn.dropdown;b.fn.dropdown=function(a){return this.each(function(){var c=b(this),e=c.data("bs.dropdown");e||c.data("bs.dropdown",e=new d(this));"string"==typeof a&&e[a].call(c)})};b.fn.dropdown.Constructor=d;b.fn.dropdown.noConflict=function(){b.fn.dropdown=a;return this};b(document).on("click.bs.dropdown.data-api",
e).on("click.bs.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.bs.dropdown.data-api",'[data-toggle="dropdown"]',d.prototype.toggle).on("keydown.bs.dropdown.data-api",'[data-toggle="dropdown"]',d.prototype.keydown).on("keydown.bs.dropdown.data-api",".dropdown-menu",d.prototype.keydown)}(jQuery);
+function(b){function f(a,c){return this.each(function(){var d=b(this),f=d.data("bs.modal"),m=b.extend({},e.DEFAULTS,d.data(),"object"==typeof a&&a);f||d.data("bs.modal",f=new e(this,m));if("string"==typeof a)f[a](c);else m.show&&f.show(c)})}var e=function(a,c){this.options=c;this.$body=b(document.body);this.$element=b(a);this.$dialog=this.$element.find(".modal-dialog");this.originalBodyPad=this.isShown=this.$backdrop=null;this.scrollbarWidth=0;this.ignoreBackdropClick=!1;this.options.remote&&this.$element.find(".modal-content").load(this.options.remote,
b.proxy(function(){this.$element.trigger("loaded.bs.modal")},this))};e.VERSION="3.3.7";e.TRANSITION_DURATION=300;e.BACKDROP_TRANSITION_DURATION=150;e.DEFAULTS={backdrop:!0,keyboard:!0,show:!0};e.prototype.toggle=function(a){return this.isShown?this.hide():this.show(a)};e.prototype.show=function(a){var c=this,d=b.Event("show.bs.modal",{relatedTarget:a});this.$element.trigger(d);this.isShown||d.isDefaultPrevented()||(this.isShown=!0,this.checkScrollbar(),this.setScrollbar(),this.$body.addClass("modal-open"),
this.escape(),this.resize(),this.$element.on("click.dismiss.bs.modal",'[data-dismiss="modal"]',b.proxy(this.hide,this)),this.$dialog.on("mousedown.dismiss.bs.modal",function(){c.$element.one("mouseup.dismiss.bs.modal",function(a){b(a.target).is(c.$element)&&(c.ignoreBackdropClick=!0)})}),this.backdrop(function(){var d=b.support.transition&&c.$element.hasClass("fade");c.$element.parent().length||c.$element.appendTo(c.$body);c.$element.show().scrollTop(0);c.adjustDialog();d&&c.$element[0].offsetWidth;
c.$element.addClass("in");c.enforceFocus();var g=b.Event("shown.bs.modal",{relatedTarget:a});d?c.$dialog.one("bsTransitionEnd",function(){c.$element.trigger("focus").trigger(g)}).emulateTransitionEnd(e.TRANSITION_DURATION):c.$element.trigger("focus").trigger(g)}))};e.prototype.hide=function(a){a&&a.preventDefault();a=b.Event("hide.bs.modal");this.$element.trigger(a);this.isShown&&!a.isDefaultPrevented()&&(this.isShown=!1,this.escape(),this.resize(),b(document).off("focusin.bs.modal"),this.$element.removeClass("in").off("click.dismiss.bs.modal").off("mouseup.dismiss.bs.modal"),
this.$dialog.off("mousedown.dismiss.bs.modal"),b.support.transition&&this.$element.hasClass("fade")?this.$element.one("bsTransitionEnd",b.proxy(this.hideModal,this)).emulateTransitionEnd(e.TRANSITION_DURATION):this.hideModal())};e.prototype.enforceFocus=function(){b(document).off("focusin.bs.modal").on("focusin.bs.modal",b.proxy(function(a){document===a.target||this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.trigger("focus")},this))};e.prototype.escape=function(){if(this.isShown&&
this.options.keyboard)this.$element.on("keydown.dismiss.bs.modal",b.proxy(function(a){27==a.which&&this.hide()},this));else this.isShown||this.$element.off("keydown.dismiss.bs.modal")};e.prototype.resize=function(){if(this.isShown)b(window).on("resize.bs.modal",b.proxy(this.handleUpdate,this));else b(window).off("resize.bs.modal")};e.prototype.hideModal=function(){var a=this;this.$element.hide();this.backdrop(function(){a.$body.removeClass("modal-open");a.resetAdjustments();a.resetScrollbar();a.$element.trigger("hidden.bs.modal")})};
e.prototype.removeBackdrop=function(){this.$backdrop&&this.$backdrop.remove();this.$backdrop=null};e.prototype.backdrop=function(a){var c=this,d=this.$element.hasClass("fade")?"fade":"";if(this.isShown&&this.options.backdrop){var f=b.support.transition&&d;this.$backdrop=b(document.createElement("div")).addClass("modal-backdrop "+d).appendTo(this.$body);this.$element.on("click.dismiss.bs.modal",b.proxy(function(a){this.ignoreBackdropClick?this.ignoreBackdropClick=!1:a.target===a.currentTarget&&("static"==
this.options.backdrop?this.$element[0].focus():this.hide())},this));f&&this.$backdrop[0].offsetWidth;this.$backdrop.addClass("in");a&&(f?this.$backdrop.one("bsTransitionEnd",a).emulateTransitionEnd(e.BACKDROP_TRANSITION_DURATION):a())}else!this.isShown&&this.$backdrop?(this.$backdrop.removeClass("in"),d=function(){c.removeBackdrop();a&&a()},b.support.transition&&this.$element.hasClass("fade")?this.$backdrop.one("bsTransitionEnd",d).emulateTransitionEnd(e.BACKDROP_TRANSITION_DURATION):d()):a&&a()};
e.prototype.handleUpdate=function(){this.adjustDialog()};e.prototype.adjustDialog=function(){var a=this.$element[0].scrollHeight>document.documentElement.clientHeight;this.$element.css({paddingLeft:!this.bodyIsOverflowing&&a?this.scrollbarWidth:"",paddingRight:this.bodyIsOverflowing&&!a?this.scrollbarWidth:""})};e.prototype.resetAdjustments=function(){this.$element.css({paddingLeft:"",paddingRight:""})};e.prototype.checkScrollbar=function(){var a=window.innerWidth;a||(a=document.documentElement.getBoundingClientRect(),
a=a.right-Math.abs(a.left));this.bodyIsOverflowing=document.body.clientWidth<a;this.scrollbarWidth=this.measureScrollbar()};e.prototype.setScrollbar=function(){var a=parseInt(this.$body.css("padding-right")||0,10);this.originalBodyPad=document.body.style.paddingRight||"";this.bodyIsOverflowing&&this.$body.css("padding-right",a+this.scrollbarWidth)};e.prototype.resetScrollbar=function(){this.$body.css("padding-right",this.originalBodyPad)};e.prototype.measureScrollbar=function(){var a=document.createElement("div");
a.className="modal-scrollbar-measure";this.$body.append(a);var c=a.offsetWidth-a.clientWidth;this.$body[0].removeChild(a);return c};var d=b.fn.modal;b.fn.modal=f;b.fn.modal.Constructor=e;b.fn.modal.noConflict=function(){b.fn.modal=d;return this};b(document).on("click.bs.modal.data-api",'[data-toggle="modal"]',function(a){var c=b(this),d=c.attr("href"),e=b(c.attr("data-target")||d&&d.replace(/.*(?=#[^\s]+$)/,""));d=e.data("bs.modal")?"toggle":b.extend({remote:!/#/.test(d)&&d},e.data(),c.data());c.is("a")&&
a.preventDefault();e.one("show.bs.modal",function(a){if(!a.isDefaultPrevented())e.one("hidden.bs.modal",function(){c.is(":visible")&&c.trigger("focus")})});f.call(e,d,this)})}(jQuery);
+function(b){var f=function(b,a){this.inState=this.$element=this.hoverState=this.timeout=this.enabled=this.options=this.type=null;this.init("tooltip",b,a)};f.VERSION="3.3.7";f.TRANSITION_DURATION=150;f.DEFAULTS={animation:!0,placement:"top",selector:!1,template:'<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>',trigger:"hover focus",title:"",delay:0,html:!1,container:!1,viewport:{selector:"body",padding:0}};f.prototype.init=function(d,a,
c){this.enabled=!0;this.type=d;this.$element=b(a);this.options=this.getOptions(c);this.$viewport=this.options.viewport&&b(b.isFunction(this.options.viewport)?this.options.viewport.call(this,this.$element):this.options.viewport.selector||this.options.viewport);this.inState={click:!1,hover:!1,focus:!1};if(this.$element[0]instanceof document.constructor&&!this.options.selector)throw Error("`selector` option must be specified when initializing "+this.type+" on the window.document object!");d=this.options.trigger.split(" ");
for(a=d.length;a--;)if(c=d[a],"click"==c)this.$element.on("click."+this.type,this.options.selector,b.proxy(this.toggle,this));else if("manual"!=c){var g="hover"==c?"mouseleave":"focusout";this.$element.on(("hover"==c?"mouseenter":"focusin")+"."+this.type,this.options.selector,b.proxy(this.enter,this));this.$element.on(g+"."+this.type,this.options.selector,b.proxy(this.leave,this))}this.options.selector?this._options=b.extend({},this.options,{trigger:"manual",selector:""}):this.fixTitle()};f.prototype.getDefaults=
function(){return f.DEFAULTS};f.prototype.getOptions=function(d){d=b.extend({},this.getDefaults(),this.$element.data(),d);d.delay&&"number"==typeof d.delay&&(d.delay={show:d.delay,hide:d.delay});return d};f.prototype.getDelegateOptions=function(){var d={},a=this.getDefaults();this._options&&b.each(this._options,function(c,b){a[c]!=b&&(d[c]=b)});return d};f.prototype.enter=function(d){var a=d instanceof this.constructor?d:b(d.currentTarget).data("bs."+this.type);a||(a=new this.constructor(d.currentTarget,
this.getDelegateOptions()),b(d.currentTarget).data("bs."+this.type,a));d instanceof b.Event&&(a.inState["focusin"==d.type?"focus":"hover"]=!0);if(a.tip().hasClass("in")||"in"==a.hoverState)a.hoverState="in";else{clearTimeout(a.timeout);a.hoverState="in";if(!a.options.delay||!a.options.delay.show)return a.show();a.timeout=setTimeout(function(){"in"==a.hoverState&&a.show()},a.options.delay.show)}};f.prototype.isInStateTrue=function(){for(var b in this.inState)if(this.inState[b])return!0;return!1};f.prototype.leave=
function(d){var a=d instanceof this.constructor?d:b(d.currentTarget).data("bs."+this.type);a||(a=new this.constructor(d.currentTarget,this.getDelegateOptions()),b(d.currentTarget).data("bs."+this.type,a));d instanceof b.Event&&(a.inState["focusout"==d.type?"focus":"hover"]=!1);if(!a.isInStateTrue()){clearTimeout(a.timeout);a.hoverState="out";if(!a.options.delay||!a.options.delay.hide)return a.hide();a.timeout=setTimeout(function(){"out"==a.hoverState&&a.hide()},a.options.delay.hide)}};f.prototype.show=
function(){var d=b.Event("show.bs."+this.type);if(this.hasContent()&&this.enabled){this.$element.trigger(d);var a=b.contains(this.$element[0].ownerDocument.documentElement,this.$element[0]);if(!d.isDefaultPrevented()&&a){var c=this;d=this.tip();a=this.getUID(this.type);this.setContent();d.attr("id",a);this.$element.attr("aria-describedby",a);this.options.animation&&d.addClass("fade");a="function"==typeof this.options.placement?this.options.placement.call(this,d[0],this.$element[0]):this.options.placement;
var g=/\s?auto?\s?/i,e=g.test(a);e&&(a=a.replace(g,"")||"top");d.detach().css({top:0,left:0,display:"block"}).addClass(a).data("bs."+this.type,this);this.options.container?d.appendTo(this.options.container):d.insertAfter(this.$element);this.$element.trigger("inserted.bs."+this.type);g=this.getPosition();var m=d[0].offsetWidth,k=d[0].offsetHeight;if(e){e=a;var h=this.getPosition(this.$viewport);a="bottom"==a&&g.bottom+k>h.bottom?"top":"top"==a&&g.top-k<h.top?"bottom":"right"==a&&g.right+m>h.width?
"left":"left"==a&&g.left-m<h.left?"right":a;d.removeClass(e).addClass(a)}g=this.getCalculatedOffset(a,g,m,k);this.applyPlacement(g,a);a=function(){var a=c.hoverState;c.$element.trigger("shown.bs."+c.type);c.hoverState=null;"out"==a&&c.leave(c)};b.support.transition&&this.$tip.hasClass("fade")?d.one("bsTransitionEnd",a).emulateTransitionEnd(f.TRANSITION_DURATION):a()}}};f.prototype.applyPlacement=function(d,a){var c=this.tip(),e=c[0].offsetWidth,f=c[0].offsetHeight,m=parseInt(c.css("margin-top"),10),
k=parseInt(c.css("margin-left"),10);isNaN(m)&&(m=0);isNaN(k)&&(k=0);d.top+=m;d.left+=k;b.offset.setOffset(c[0],b.extend({using:function(a){c.css({top:Math.round(a.top),left:Math.round(a.left)})}},d),0);c.addClass("in");k=c[0].offsetWidth;var h=c[0].offsetHeight;"top"==a&&h!=f&&(d.top=d.top+f-h);var n=this.getViewportAdjustedDelta(a,d,k,h);n.left?d.left+=n.left:d.top+=n.top;e=(m=/top|bottom/.test(a))?2*n.left-e+k:2*n.top-f+h;f=m?"offsetWidth":"offsetHeight";c.offset(d);this.replaceArrow(e,c[0][f],
m)};f.prototype.replaceArrow=function(b,a,c){this.arrow().css(c?"left":"top",50*(1-b/a)+"%").css(c?"top":"left","")};f.prototype.setContent=function(){var b=this.tip(),a=this.getTitle();b.find(".tooltip-inner")[this.options.html?"html":"text"](a);b.removeClass("fade in top bottom left right")};f.prototype.hide=function(d){function a(){"in"!=c.hoverState&&e.detach();c.$element&&c.$element.removeAttr("aria-describedby").trigger("hidden.bs."+c.type);d&&d()}var c=this,e=b(this.$tip),l=b.Event("hide.bs."+
this.type);this.$element.trigger(l);if(!l.isDefaultPrevented())return e.removeClass("in"),b.support.transition&&e.hasClass("fade")?e.one("bsTransitionEnd",a).emulateTransitionEnd(f.TRANSITION_DURATION):a(),this.hoverState=null,this};f.prototype.fixTitle=function(){var b=this.$element;(b.attr("title")||"string"!=typeof b.attr("data-original-title"))&&b.attr("data-original-title",b.attr("title")||"").attr("title","")};f.prototype.hasContent=function(){return this.getTitle()};f.prototype.getPosition=
function(d){d=d||this.$element;var a=d[0],c="BODY"==a.tagName,e=a.getBoundingClientRect();null==e.width&&(e=b.extend({},e,{width:e.right-e.left,height:e.bottom-e.top}));a=window.SVGElement&&a instanceof window.SVGElement;a=c?{top:0,left:0}:a?null:d.offset();d={scroll:c?document.documentElement.scrollTop||document.body.scrollTop:d.scrollTop()};c=c?{width:b(window).width(),height:b(window).height()}:null;return b.extend({},e,d,c,a)};f.prototype.getCalculatedOffset=function(b,a,c,e){return"bottom"==
b?{top:a.top+a.height,left:a.left+a.width/2-c/2}:"top"==b?{top:a.top-e,left:a.left+a.width/2-c/2}:"left"==b?{top:a.top+a.height/2-e/2,left:a.left-c}:{top:a.top+a.height/2-e/2,left:a.left+a.width}};f.prototype.getViewportAdjustedDelta=function(b,a,c,e){var d={top:0,left:0};if(!this.$viewport)return d;var f=this.options.viewport&&this.options.viewport.padding||0,g=this.getPosition(this.$viewport);/right|left/.test(b)?(c=a.top-f-g.scroll,a=a.top+f-g.scroll+e,c<g.top?d.top=g.top-c:a>g.top+g.height&&(d.top=
g.top+g.height-a)):(e=a.left-f,a=a.left+f+c,e<g.left?d.left=g.left-e:a>g.right&&(d.left=g.left+g.width-a));return d};f.prototype.getTitle=function(){var b=this.$element,a=this.options;return b.attr("data-original-title")||("function"==typeof a.title?a.title.call(b[0]):a.title)};f.prototype.getUID=function(b){do b+=~~(1E6*Math.random());while(document.getElementById(b));return b};f.prototype.tip=function(){if(!this.$tip&&(this.$tip=b(this.options.template),1!=this.$tip.length))throw Error(this.type+
" `template` option must consist of exactly 1 top-level element!");return this.$tip};f.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".tooltip-arrow")};f.prototype.enable=function(){this.enabled=!0};f.prototype.disable=function(){this.enabled=!1};f.prototype.toggleEnabled=function(){this.enabled=!this.enabled};f.prototype.toggle=function(d){var a=this;d&&(a=b(d.currentTarget).data("bs."+this.type),a||(a=new this.constructor(d.currentTarget,this.getDelegateOptions()),b(d.currentTarget).data("bs."+
this.type,a)));d?(a.inState.click=!a.inState.click,a.isInStateTrue()?a.enter(a):a.leave(a)):a.tip().hasClass("in")?a.leave(a):a.enter(a)};f.prototype.destroy=function(){var b=this;clearTimeout(this.timeout);this.hide(function(){b.$element.off("."+b.type).removeData("bs."+b.type);b.$tip&&b.$tip.detach();b.$tip=null;b.$arrow=null;b.$viewport=null;b.$element=null})};var e=b.fn.tooltip;b.fn.tooltip=function(d){return this.each(function(){var a=b(this),c=a.data("bs.tooltip"),e="object"==typeof d&&d;if(c||
!/destroy|hide/.test(d))if(c||a.data("bs.tooltip",c=new f(this,e)),"string"==typeof d)c[d]()})};b.fn.tooltip.Constructor=f;b.fn.tooltip.noConflict=function(){b.fn.tooltip=e;return this}}(jQuery);
+function(b){var f=function(b,a){this.init("popover",b,a)};if(!b.fn.tooltip)throw Error("Popover requires tooltip.js");f.VERSION="3.3.7";f.DEFAULTS=b.extend({},b.fn.tooltip.Constructor.DEFAULTS,{placement:"right",trigger:"click",content:"",template:'<div class="popover" role="tooltip"><div class="arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>'});f.prototype=b.extend({},b.fn.tooltip.Constructor.prototype);f.prototype.constructor=f;f.prototype.getDefaults=function(){return f.DEFAULTS};
f.prototype.setContent=function(){var b=this.tip(),a=this.getTitle(),c=this.getContent();b.find(".popover-title")[this.options.html?"html":"text"](a);b.find(".popover-content").children().detach().end()[this.options.html?"string"==typeof c?"html":"append":"text"](c);b.removeClass("fade top bottom left right in");b.find(".popover-title").html()||b.find(".popover-title").hide()};f.prototype.hasContent=function(){return this.getTitle()||this.getContent()};f.prototype.getContent=function(){var b=this.$element,
a=this.options;return b.attr("data-content")||("function"==typeof a.content?a.content.call(b[0]):a.content)};f.prototype.arrow=function(){return this.$arrow=this.$arrow||this.tip().find(".arrow")};var e=b.fn.popover;b.fn.popover=function(d){return this.each(function(){var a=b(this),c=a.data("bs.popover"),e="object"==typeof d&&d;if(c||!/destroy|hide/.test(d))if(c||a.data("bs.popover",c=new f(this,e)),"string"==typeof d)c[d]()})};b.fn.popover.Constructor=f;b.fn.popover.noConflict=function(){b.fn.popover=
e;return this}}(jQuery);
+function(b){function f(a,c){this.$body=b(document.body);this.$scrollElement=b(a).is(document.body)?b(window):b(a);this.options=b.extend({},f.DEFAULTS,c);this.selector=(this.options.target||"")+" .nav li > a";this.offsets=[];this.targets=[];this.activeTarget=null;this.scrollHeight=0;this.$scrollElement.on("scroll.bs.scrollspy",b.proxy(this.process,this));this.refresh();this.process()}function e(a){return this.each(function(){var c=b(this),d=c.data("bs.scrollspy"),e="object"==typeof a&&a;d||c.data("bs.scrollspy",
d=new f(this,e));if("string"==typeof a)d[a]()})}f.VERSION="3.3.7";f.DEFAULTS={offset:10};f.prototype.getScrollHeight=function(){return this.$scrollElement[0].scrollHeight||Math.max(this.$body[0].scrollHeight,document.documentElement.scrollHeight)};f.prototype.refresh=function(){var a=this,c="offset",d=0;this.offsets=[];this.targets=[];this.scrollHeight=this.getScrollHeight();b.isWindow(this.$scrollElement[0])||(c="position",d=this.$scrollElement.scrollTop());this.$body.find(this.selector).map(function(){var a=
b(this);a=a.data("target")||a.attr("href");var e=/^#./.test(a)&&b(a);return e&&e.length&&e.is(":visible")&&[[e[c]().top+d,a]]||null}).sort(function(a,b){return a[0]-b[0]}).each(function(){a.offsets.push(this[0]);a.targets.push(this[1])})};f.prototype.process=function(){var a=this.$scrollElement.scrollTop()+this.options.offset,b=this.getScrollHeight(),d=this.options.offset+b-this.$scrollElement.height(),e=this.offsets,f=this.targets,k=this.activeTarget,h;this.scrollHeight!=b&&this.refresh();if(a>=
d)return k!=(h=f[f.length-1])&&this.activate(h);if(k&&a<e[0])return this.activeTarget=null,this.clear();for(h=e.length;h--;)k!=f[h]&&a>=e[h]&&(void 0===e[h+1]||a<e[h+1])&&this.activate(f[h])};f.prototype.activate=function(a){this.activeTarget=a;this.clear();a=b(this.selector+'[data-target="'+a+'"],'+this.selector+'[href="'+a+'"]').parents("li").addClass("active");a.parent(".dropdown-menu").length&&(a=a.closest("li.dropdown").addClass("active"));a.trigger("activate.bs.scrollspy")};f.prototype.clear=
function(){b(this.selector).parentsUntil(this.options.target,".active").removeClass("active")};var d=b.fn.scrollspy;b.fn.scrollspy=e;b.fn.scrollspy.Constructor=f;b.fn.scrollspy.noConflict=function(){b.fn.scrollspy=d;return this};b(window).on("load.bs.scrollspy.data-api",function(){b('[data-spy="scroll"]').each(function(){var a=b(this);e.call(a,a.data())})})}(jQuery);
+function(b){function f(a){return this.each(function(){var c=b(this),d=c.data("bs.tab");d||c.data("bs.tab",d=new e(this));if("string"==typeof a)d[a]()})}var e=function(a){this.element=b(a)};e.VERSION="3.3.7";e.TRANSITION_DURATION=150;e.prototype.show=function(){var a=this.element,d=a.closest("ul:not(.dropdown-menu)"),e=a.data("target");e||(e=(e=a.attr("href"))&&e.replace(/.*(?=#[^\s]*$)/,""));if(!a.parent("li").hasClass("active")){var f=d.find(".active:last a"),k=b.Event("hide.bs.tab",{relatedTarget:a[0]}),
h=b.Event("show.bs.tab",{relatedTarget:f[0]});f.trigger(k);a.trigger(h);h.isDefaultPrevented()||k.isDefaultPrevented()||(e=b(e),this.activate(a.closest("li"),d),this.activate(e,e.parent(),function(){f.trigger({type:"hidden.bs.tab",relatedTarget:a[0]});a.trigger({type:"shown.bs.tab",relatedTarget:f[0]})}))}};e.prototype.activate=function(a,d,f){function c(){g.removeClass("active").find("> .dropdown-menu > .active").removeClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!1);a.addClass("active").find('[data-toggle="tab"]').attr("aria-expanded",
!0);h?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu").length&&a.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!0);f&&f()}var g=d.find("> .active"),h=f&&b.support.transition&&(g.length&&g.hasClass("fade")||!!d.find("> .fade").length);g.length&&h?g.one("bsTransitionEnd",c).emulateTransitionEnd(e.TRANSITION_DURATION):c();g.removeClass("in")};var d=b.fn.tab;b.fn.tab=f;b.fn.tab.Constructor=e;b.fn.tab.noConflict=function(){b.fn.tab=
d;return this};var a=function(a){a.preventDefault();f.call(b(this),"show")};b(document).on("click.bs.tab.data-api",'[data-toggle="tab"]',a).on("click.bs.tab.data-api",'[data-toggle="pill"]',a)}(jQuery);
+function(b){function f(a){return this.each(function(){var c=b(this),d=c.data("bs.affix"),f="object"==typeof a&&a;d||c.data("bs.affix",d=new e(this,f));if("string"==typeof a)d[a]()})}var e=function(a,c){this.options=b.extend({},e.DEFAULTS,c);this.$target=b(this.options.target).on("scroll.bs.affix.data-api",b.proxy(this.checkPosition,this)).on("click.bs.affix.data-api",b.proxy(this.checkPositionWithEventLoop,this));this.$element=b(a);this.pinnedOffset=this.unpin=this.affixed=null;this.checkPosition()};
e.VERSION="3.3.7";e.RESET="affix affix-top affix-bottom";e.DEFAULTS={offset:0,target:window};e.prototype.getState=function(a,b,d,e){var c=this.$target.scrollTop(),f=this.$element.offset(),g=this.$target.height();if(null!=d&&"top"==this.affixed)return c<d?"top":!1;if("bottom"==this.affixed)return null!=d?c+this.unpin<=f.top?!1:"bottom":c+g<=a-e?!1:"bottom";var l=null==this.affixed;f=l?c:f.top;return null!=d&&c<=d?"top":null!=e&&f+(l?g:b)>=a-e?"bottom":!1};e.prototype.getPinnedOffset=function(){if(this.pinnedOffset)return this.pinnedOffset;
this.$element.removeClass(e.RESET).addClass("affix");var a=this.$target.scrollTop();return this.pinnedOffset=this.$element.offset().top-a};e.prototype.checkPositionWithEventLoop=function(){setTimeout(b.proxy(this.checkPosition,this),1)};e.prototype.checkPosition=function(){if(this.$element.is(":visible")){var a=this.$element.height(),c=this.options.offset,d=c.top,f=c.bottom,m=Math.max(b(document).height(),b(document.body).height());"object"!=typeof c&&(f=d=c);"function"==typeof d&&(d=c.top(this.$element));
"function"==typeof f&&(f=c.bottom(this.$element));c=this.getState(m,a,d,f);if(this.affixed!=c){null!=this.unpin&&this.$element.css("top","");d="affix"+(c?"-"+c:"");var k=b.Event(d+".bs.affix");this.$element.trigger(k);if(k.isDefaultPrevented())return;this.affixed=c;this.unpin="bottom"==c?this.getPinnedOffset():null;this.$element.removeClass(e.RESET).addClass(d).trigger(d.replace("affix","affixed")+".bs.affix")}"bottom"==c&&this.$element.offset({top:m-a-f})}};var d=b.fn.affix;b.fn.affix=f;b.fn.affix.Constructor=
e;b.fn.affix.noConflict=function(){b.fn.affix=d;return this};b(window).on("load",function(){b('[data-spy="affix"]').each(function(){var a=b(this),c=a.data();c.offset=c.offset||{};null!=c.offsetBottom&&(c.offset.bottom=c.offsetBottom);null!=c.offsetTop&&(c.offset.top=c.offsetTop);f.call(a,c)})})}(jQuery);